// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_4mImHod4x09QkPo5xsy4eKndWcc_qo',
    appId: '1:195122960711:web:aea64bcc8787080efb5462',
    messagingSenderId: '195122960711',
    projectId: 'rickmorty-265b8',
    authDomain: 'rickmorty-265b8.firebaseapp.com',
    storageBucket: 'rickmorty-265b8.firebasestorage.app',
    measurementId: 'G-6DSVR7JTB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4SFzyFZXuNxuVyX_9ywxE1ONbp9mQWo',
    appId: '1:195122960711:android:ed6e5473d9c6fa03fb5462',
    messagingSenderId: '195122960711',
    projectId: 'rickmorty-265b8',
    storageBucket: 'rickmorty-265b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCppjj_stCNWrBeNq8AXPshLRHqtAXGsF0',
    appId: '1:195122960711:ios:85d65e26c081e7dcfb5462',
    messagingSenderId: '195122960711',
    projectId: 'rickmorty-265b8',
    storageBucket: 'rickmorty-265b8.firebasestorage.app',
    iosBundleId: 'com.example.morty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCppjj_stCNWrBeNq8AXPshLRHqtAXGsF0',
    appId: '1:195122960711:ios:85d65e26c081e7dcfb5462',
    messagingSenderId: '195122960711',
    projectId: 'rickmorty-265b8',
    storageBucket: 'rickmorty-265b8.firebasestorage.app',
    iosBundleId: 'com.example.morty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_4mImHod4x09QkPo5xsy4eKndWcc_qo',
    appId: '1:195122960711:web:ba4733ceda3ee6c5fb5462',
    messagingSenderId: '195122960711',
    projectId: 'rickmorty-265b8',
    authDomain: 'rickmorty-265b8.firebaseapp.com',
    storageBucket: 'rickmorty-265b8.firebasestorage.app',
    measurementId: 'G-GZCLCKSP08',
  );
}
